// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApu6dcDvBa2RsSkqjAEg_uomsx4zA61PY',
    appId: '1:44081344816:web:959a96e013f397747418f5',
    messagingSenderId: '44081344816',
    projectId: 'smart-hydroponic-14bcf',
    authDomain: 'smart-hydroponic-14bcf.firebaseapp.com',
    storageBucket: 'smart-hydroponic-14bcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIhqKK-UMKd_Jmw4WGEWojye8P_zNBOro',
    appId: '1:44081344816:android:1df04ac86c6a13097418f5',
    messagingSenderId: '44081344816',
    projectId: 'smart-hydroponic-14bcf',
    storageBucket: 'smart-hydroponic-14bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM1Dy83eObVsunTF2B0s87JA1H5BBs0ko',
    appId: '1:44081344816:ios:f086ca8b932eb7657418f5',
    messagingSenderId: '44081344816',
    projectId: 'smart-hydroponic-14bcf',
    storageBucket: 'smart-hydroponic-14bcf.firebasestorage.app',
    iosBundleId: 'com.example.smartHydroponic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM1Dy83eObVsunTF2B0s87JA1H5BBs0ko',
    appId: '1:44081344816:ios:f086ca8b932eb7657418f5',
    messagingSenderId: '44081344816',
    projectId: 'smart-hydroponic-14bcf',
    storageBucket: 'smart-hydroponic-14bcf.firebasestorage.app',
    iosBundleId: 'com.example.smartHydroponic',
  );
}